2020-12-22 22:52:44,090 ERROR: Exception on /fetch [POST] [in C:\Users\44738\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\44738\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\sqlalchemy\orm\relationships.py", line 2460, in _determine_joins
    consider_as_foreign_keys=consider_as_foreign_keys,
  File "<string>", line 2, in join_condition
  File "<string>", line 2, in _join_condition
  File "C:\Users\44738\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\sqlalchemy\util\deprecations.py", line 128, in warned
    return fn(*args, **kwargs)
  File "C:\Users\44738\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\sqlalchemy\sql\selectable.py", line 952, in _join_condition
    % (a.description, b.description, hint)
sqlalchemy.exc.NoForeignKeysError: Can't find any foreign key relationships between 'contact_groups' and 'association'.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\44738\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\44738\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\44738\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\44738\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\44738\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\44738\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\44738\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\44738\OneDrive\Documents\Web\app\main\routes.py", line 59, in fetch
    group = ContactGroups.query.filter_by(group_name = group_name).first()
  File "C:\Users\44738\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask_sqlalchemy\__init__.py", line 517, in __get__
    mapper = orm.class_mapper(type)
  File "C:\Users\44738\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\sqlalchemy\orm\base.py", line 444, in class_mapper
    mapper = _inspect_mapped_class(class_, configure=configure)
  File "C:\Users\44738\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\sqlalchemy\orm\base.py", line 423, in _inspect_mapped_class
    mapper._configure_all()
  File "C:\Users\44738\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\sqlalchemy\orm\mapper.py", line 1337, in _configure_all
    configure_mappers()
  File "C:\Users\44738\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\sqlalchemy\orm\mapper.py", line 3255, in configure_mappers
    mapper._post_configure_properties()
  File "C:\Users\44738\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\sqlalchemy\orm\mapper.py", line 1950, in _post_configure_properties
    prop.init()
  File "C:\Users\44738\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\sqlalchemy\orm\interfaces.py", line 196, in init
    self.do_init()
  File "C:\Users\44738\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\sqlalchemy\orm\relationships.py", line 1936, in do_init
    self._setup_join_conditions()
  File "C:\Users\44738\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\sqlalchemy\orm\relationships.py", line 2016, in _setup_join_conditions
    can_be_synced_fn=self._columns_are_mapped,
  File "C:\Users\44738\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\sqlalchemy\orm\relationships.py", line 2360, in __init__
    self._determine_joins()
  File "C:\Users\44738\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\sqlalchemy\orm\relationships.py", line 2490, in _determine_joins
    from_=nfe,
  File "C:\Users\44738\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\sqlalchemy\util\compat.py", line 178, in raise_
    raise exception
sqlalchemy.exc.NoForeignKeysError: Could not determine join condition between parent/child tables on relationship SkypeContacts.groups - there are no foreign keys linking these tables via secondary table 'association'.  Ensure that referencing columns are associated with a ForeignKey or ForeignKeyConstraint, or specify 'primaryjoin' and 'secondaryjoin' expressions.
2020-12-22 22:57:31,782 INFO: Project startup [in C:\Users\44738\OneDrive\Documents\Web\app\__init__.py:66]
2020-12-22 22:57:35,937 INFO: Project startup [in C:\Users\44738\OneDrive\Documents\Web\app\__init__.py:66]
2020-12-22 22:57:43,942 INFO: Project startup [in C:\Users\44738\OneDrive\Documents\Web\app\__init__.py:66]
2020-12-22 22:57:48,017 INFO: Project startup [in C:\Users\44738\OneDrive\Documents\Web\app\__init__.py:66]
2020-12-22 22:57:53,815 INFO: Project startup [in C:\Users\44738\OneDrive\Documents\Web\app\__init__.py:66]
2020-12-22 22:58:04,045 INFO: Project startup [in C:\Users\44738\OneDrive\Documents\Web\app\__init__.py:66]
2020-12-22 22:58:09,211 INFO: Project startup [in C:\Users\44738\OneDrive\Documents\Web\app\__init__.py:66]
2020-12-22 22:58:21,009 INFO: Project startup [in C:\Users\44738\OneDrive\Documents\Web\app\__init__.py:66]
2020-12-22 22:58:24,866 INFO: Project startup [in C:\Users\44738\OneDrive\Documents\Web\app\__init__.py:66]
2020-12-22 22:58:28,806 INFO: Project startup [in C:\Users\44738\OneDrive\Documents\Web\app\__init__.py:66]
2020-12-22 22:58:32,398 INFO: Project startup [in C:\Users\44738\OneDrive\Documents\Web\app\__init__.py:66]
2020-12-22 22:58:37,950 INFO: Project startup [in C:\Users\44738\OneDrive\Documents\Web\app\__init__.py:66]
2020-12-22 22:58:45,580 INFO: Project startup [in C:\Users\44738\OneDrive\Documents\Web\app\__init__.py:66]
2020-12-22 22:58:49,326 INFO: Project startup [in C:\Users\44738\OneDrive\Documents\Web\app\__init__.py:66]
2020-12-22 22:59:13,638 INFO: Project startup [in C:\Users\44738\OneDrive\Documents\Web\app\__init__.py:66]
2020-12-22 22:59:25,807 INFO: Project startup [in C:\Users\44738\OneDrive\Documents\Web\app\__init__.py:66]
2020-12-22 22:59:59,686 INFO: Project startup [in C:\Users\44738\OneDrive\Documents\Web\app\__init__.py:66]
2020-12-22 23:00:06,717 INFO: Project startup [in C:\Users\44738\OneDrive\Documents\Web\app\__init__.py:66]
2020-12-22 23:00:11,415 INFO: Project startup [in C:\Users\44738\OneDrive\Documents\Web\app\__init__.py:66]
2020-12-22 23:00:14,496 INFO: Project startup [in C:\Users\44738\OneDrive\Documents\Web\app\__init__.py:66]
2020-12-22 23:00:44,299 INFO: Project startup [in C:\Users\44738\OneDrive\Documents\Web\app\__init__.py:66]
2020-12-22 23:00:52,074 INFO: Project startup [in C:\Users\44738\OneDrive\Documents\Web\app\__init__.py:66]
2020-12-22 23:02:03,796 INFO: Project startup [in C:\Users\44738\OneDrive\Documents\Web\app\__init__.py:66]
2020-12-22 23:02:09,470 INFO: Project startup [in C:\Users\44738\OneDrive\Documents\Web\app\__init__.py:66]
2020-12-22 23:02:14,998 INFO: Project startup [in C:\Users\44738\OneDrive\Documents\Web\app\__init__.py:66]
2020-12-22 23:02:44,159 INFO: Project startup [in C:\Users\44738\OneDrive\Documents\Web\app\__init__.py:66]
2020-12-22 23:02:57,261 INFO: Project startup [in C:\Users\44738\OneDrive\Documents\Web\app\__init__.py:66]
2020-12-22 23:04:40,909 INFO: Project startup [in C:\Users\44738\OneDrive\Documents\Web\app\__init__.py:66]
2020-12-22 23:05:51,286 INFO: Project startup [in C:\Users\44738\OneDrive\Documents\Web\app\__init__.py:66]
2020-12-22 23:06:00,592 INFO: Project startup [in C:\Users\44738\OneDrive\Documents\Web\app\__init__.py:66]
2020-12-22 23:06:05,901 INFO: Project startup [in C:\Users\44738\OneDrive\Documents\Web\app\__init__.py:66]
2020-12-22 23:06:09,862 INFO: Project startup [in C:\Users\44738\OneDrive\Documents\Web\app\__init__.py:66]
2020-12-22 23:06:57,468 INFO: Project startup [in C:\Users\44738\OneDrive\Documents\Web\app\__init__.py:66]
2020-12-22 23:08:10,232 INFO: Project startup [in C:\Users\44738\OneDrive\Documents\Web\app\__init__.py:66]
2020-12-22 23:10:17,386 INFO: Project startup [in C:\Users\44738\OneDrive\Documents\Web\app\__init__.py:66]
